version: '3'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: to_do_list
      POSTGRES_PASSWORD: to_do_list
      POSTGRES_DB: to_do_list
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

  to_do_list:
    build:
      context: .
    container_name: to_do_list
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    environment:
      SECRET_KEY: secret_key
      DEBUG: True
      POSTGRES_DB: to_do_list
      POSTGRES_USER: to_do_list
      POSTGRES_PASSWORD: to_do_list
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    volumes:
      - ./:/app/

volumes:
  postgres_db_data:
